---
version: "2.0"

services:
  app:
    image: dimokus88/defund:1.0.3

    
    env:
     - "my_root_password=" # пароль root для подключения по ssh
     - "MONIKER=" # имя ноды
     - "MNEMONIC=" # seed фраза от тестового кошелька с defund
     #- "LINK_KEY=" # ссылка на размещенный pirv-validator_key.json (прямое скачивание).
     - "LINK_ADDRBOOK=https://raw.githubusercontent.com/sowell-owen/addrbooks/main/defund/addrbook.json"
     - "SNAP_RPC=http://51.91.208.59:26657"
     
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
        
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 4Gi
        storage:
          size: 100Gi
        
        
  placement:
    akash: 
      attributes:
        host: akash
      signedBy:
        anyOf:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
